imagecache_get_profile:
  url:    /sfImageCache/:cache_name/get
  params: { module: imagecache, action: get }
  
imagecache_get:
  url:    /sfImageCache/get
  params: { module: imagecache, action: get }